version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql-lealtad
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: programalealtad
    ports:
      - "3306:3306"
    networks:
      - appnet

  backend:
    build: .
    container_name: programa-lealtad
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - appnet
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/programalealtad?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: T9YpN3vUeXz6mCkR7qL2bVtA8sDfJwGh

networks:
  appnet:
