version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql-lealtad
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: programalealtad
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: programa-lealtad
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/programalealtad?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: T9YpN3vUeXz6mCkR7qL2bVtA8sDfJwGh
    restart: on-failure

networks:
  appnet:

volumes:
  mysql_data:

